var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/personas/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fgg~6j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_082shsf.js")
R.c("server/chunks/ssr/[root-of-the-server]__02kuxev._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/_08hfbel._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_personas_page_actions_08fq21v.js")
R.m(83859)
module.exports=R.m(83859).exports
